# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-Instrument
version:      0.01
version_from: lib/Apache2/Instrument.pm
installdirs:  site
requires:
    mod_perl:                      2
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
